name: music_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^11.1.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1
  flutter_secure_storage: ^10.0.0
  just_audio: ^0.10.5
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # Logger
  logger: ^2.5.0

  # OAuth
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  jwt_decoder: ^2.0.1
  
  # Localization
  intl: ^0.20.2
  
  # Downloads & Storage
  path_provider: ^2.1.5
  
  # Offline Mode - Hive Database (compatible with auto_route)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network connectivity
  connectivity_plus: ^6.1.4

  # Share
  share_plus: ^12.0.1

  # Video player
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.4.14
  
  # Testing
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/
    - assets/video/
